services:
  food-match:
    image: tigercxx/food-match:latest
    build:
      context: ./food-match
      dockerfile: Dockerfile
      args:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_PUBLIC_HOSTNAME=${R2_PUBLIC_HOSTNAME}
    ports:
      - 3000:3000
    env_file:
      - .env
  ml-service:
    image: tigercxx/ml-service:latest
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://root:root@postgres:5432/food-match?schema=public
    depends_on:
      - postgres

  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-volume:/data

  postgres:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=food-match
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
  redis-volume:
