export const donationsData = [
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'This is mock data',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
]
