export const donationsData = [
  {
    name: 'Donation of food',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'Donation of food',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'Donation of food',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },
  {
    name: 'Donation of food',
    tagsIds: ['tag1', 'tag2'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of non-perishable food items',
    expiry: '2024-12-31T23:59:59.999Z',
    quantity: '10kg',
    passCode: '12345',
    donorId: 'some-donor-id',
  },

  {
    name: 'Donation of clothes',
    tagsIds: ['tag3', 'tag4'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of winter clothing items',
    expiry: '2024-11-30T23:59:59.999Z',
    quantity: '20 items',
    passCode: '67890',
    donorId: 'another-donor-id',
  },
  {
    name: 'Donation of clothes',
    tagsIds: ['tag3', 'tag4'],
    imageUrls: ['/images/luncheon_meat.png'],
    description: 'A donation of winter clothing items',
    expiry: '2024-11-30T23:59:59.999Z',
    quantity: '20 items',
    passCode: '67890',
    donorId: 'another-donor-id',
  },
]
